### ISSUE TITLE
Weird MongoDB error when running the rest-fights service with Quarkus dev

### ISSUE THREAD

**Issue by ingmarfjolla** [quarkusio/quarkus-super-heroes#752]
**Describe the bug**
hello! 

When I try to run the rest-fights service with `./mvnw quarkus:dev`  I get a stack trace like this: 

```18:11:45 INFO  [or.mo.dr.client] (Quarkus Main Thread) MongoClient with metadata {"driver": {"name": "mongo-java-driver|sync", "version": "4.11.1"}, "os": {"type": "Darwin", "name": "Mac OS X", "architecture": "aarch64", "version": "14.3.1"}, "platform": "Java/Homebrew/17.0.8.1+0"} created with settings MongoClientSettings{readPreference=primary, writeConcern=WriteConcern{w=null, wTimeout=null ms, journal=null}, retryWrites=true, retryReads=true, readConcern=ReadConcern{level=null}, credential=null, transportSettings=null, streamFactoryFactory=null, commandListeners=[], codecRegistry=ProvidersCodecRegistry{codecProviders=[ValueCodecProvider{}, BsonValueCodecProvider{}, DBRefCodecProvider{}, DBObjectCodecProvider{}, DocumentCodecProvider{}, CollectionCodecProvider{}, IterableCodecProvider{}, MapCodecProvider{}, GeoJsonCodecProvider{}, GridFSFileCodecProvider{}, Jsr310CodecProvider{}, JsonObjectCodecProvider{}, BsonCodecProvider{}, EnumCodecProvider{}, com.mongodb.client.model.mql.ExpressionCodecProvider@69d5e09e, com.mongodb.Jep395RecordCodecProvider@282b2699, com.mongodb.KotlinCodecProvider@96a0682]}, loggerSettings=LoggerSettings{maxDocumentLength=1000}, clusterSettings={hosts=[mongo-yexv5:27017], srvServiceName=mongodb, mode=SINGLE, requiredClusterType=UNKNOWN, requiredReplicaSetName='null', serverSelector='null', clusterListeners='[]', serverSelectionTimeout='30000 ms', localThreshold='15 ms'}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, receiveBufferSize=0, proxySettings=ProxySettings{host=null, port=null, username=null, password=null}}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=10000, receiveBufferSize=0, proxySettings=ProxySettings{host=null, port=null, username=null, password=null}}, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000, connectionPoolListeners=[], maxConnecting=2}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500, serverListeners='[]', serverMonitorListeners='[]'}, sslSettings=SslSettings{enabled=false, invalidHostNameAllowed=false, context=null}, applicationName='null', compressorList=[], uuidRepresentation=UNSPECIFIED, serverApi=null, autoEncryptionSettings=null, dnsClient=null, inetAddressResolver=null, contextProvider=null}

18:11:45 INFO  [or.mo.dr.cluster] (cluster-ClusterId{value='65f224a1141b7478a47c5e8f', description='null'}-mongo-yexv5:27017) Exception in monitor thread while connecting to server mongo-yexv5:27017: com.mongodb.MongoSocketException: mongo-yexv5: nodename nor servname provided, or not known
	at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:221)
	at com.mongodb.internal.connection.ServerAddressWithResolver.getSocketAddresses(ServerAddressWithResolver.java:68)
	at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:100)
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:78)
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:211)
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:196)
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:156)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.UnknownHostException: mongo-yexv5: nodename nor servname provided, or not known
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:934)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1543)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
	at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:213)
	... 7 more


18:11:45 INFO  [or.mo.dr.cluster] (Quarkus Main Thread) No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=mongo-yexv5:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketException: mongo-yexv5: nodename nor servname provided, or not known}, caused by {java.net.UnknownHostException: mongo-yexv5: nodename nor servname provided, or not known}}]}. Waiting for 30000 ms before timing out
18:11:45 INFO  [or.mo.dr.cluster] (cluster-ClusterId{value='65f224a1141b7478a47c5e8f', description='null'}-mongo-yexv5:27017) Exception in monitor thread while connecting to server mongo-yexv5:27017: com.mongodb.MongoSocketException: mongo-yexv5
	at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:221)
	at com.mongodb.internal.connection.ServerAddressWithResolver.getSocketAddresses(ServerAddressWithResolver.java:68)
	at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:100)
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:78)
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:211)
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:196)
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:156)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.UnknownHostException: mongo-yexv5
	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:801)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
	at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:213)
	... 7 more
```

Now, I noticed that if I manually start a mongoDB container (and then also provide the mongoDB connection string, user, password in an app properties) that error goes away and it seems to be working. 

But, when I try to initiate a fight I get a super similar error for kafka: 

```java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.net.UnknownHostException: kafka-c2mfg: nodename nor servname provided, or not known```

**To Reproduce**
1. start the downstream services with this command : ```docker compose -f rest-heroes/deploy/docker-compose/java17.yml -f rest-villains/deploy/docker-compose/java17.yml -f rest-narration/deploy/docker-compose/java17.yml -f grpc-locations/deploy/docker-compose/java17.yml up --remove-orphans```
2. Start the rest-fights service with `./mvnw quarkus:dev` 
3. See error

**Expected behavior**
Starting with no issues, unless I missed something in the docs

**Desktop (please complete the following information):**
 - OS: Apple M1 Mac OS Sonoma 14.3.1
 - Browser: Firefox/Chrome
 - Version: openjdk 17.0.8.1 2023-08-24 

Let me know if you need more info, or if I just completely missed something in the docs! Thanks

**Comment by ingmarfjolla** [comment]
ah I didn't see that issue, thank you so much!

**Comment by ingmarfjolla** [comment]
Do you happen to know if getting an issue in the frontend like this with Quarkus dev:

```
ERROR
Request failed with status code 404
AxiosError@http://localhost:3000/static/js/bundle.js:59623:18
settle@http://localhost:3000/static/js/bundle.js:60276:12
onloadend@http://localhost:3000/static/js/bundle.js:58938:66
ERROR
Request failed with status code 404
AxiosError@http://localhost:3000/static/js/bundle.js:59623:18
settle@http://localhost:3000/static/js/bundle.js:60276:12
onloadend@http://localhost:3000/static/js/bundle.js:58938:66
```
is related to the issue? I started the frontend with the same `./mvnw quarkus:dev -Dquarkus.profile=no-microcks` but on localhost:3000 I keep getting that error (with or without the added profile). Though interestingly if I go to localhost:8080 it works fine so maybe I did something else wrong

**Comment by edeandrea** [comment]
Yeah port 8080 is the correct port, not 3000. It's a quarkus app.

**Comment by holly-cummins** [comment]
> Yeah port 8080 is the correct port, not 3000. It's a quarkus app.

@ingmarfjolla, to add a bit more context to what you're seeing, a Quarkus extension called Quinoa is handling the integration between the front and back ends. Under the covers, it starts the javascript live coding server on port 3000, and then it proxies requests to it. But if you access things directly on 3000, they won't have the right back end services because you're only seeing the thin front-end layer. https://quarkus.io/blog/quinoa-modern-ui-with-no-hassle/ explains a bit more about Quinoa.

**Comment by ingmarfjolla** [comment]
@holly-cummins thanks for the added context!

**Comment by edeandrea** [comment]
@ingmarfjolla am I ok to close out this issue?

**Comment by ingmarfjolla** [comment]
@edeandrea yep, sounds good to me
